# Site settings
title              : "Computational Research Day"
description        : ""
publisher          : "Northwestern University Libraries"
url                :
baseurl            :


# Editorial
editors:
  name             : "NUIT Research Computing"
  avatar           : "/assets/images/nuit-avatar.png"
  bio              : "Providing campus researchers across all disciplines access to computing resources and consulting services to support innovative research."
  street_address   : "1970 Campus Drive"
  town_zip         : "Evanston, IL 60640"
  email            : "consultant@northwestern.edu"
  phone            : "847-367-5555"
  uri              : "http://www.it.northwestern.edu/research/"
  home             :
  facebook         :
  github           :
  twitter          : "NUITResearch"
  youtube          : "https://www.youtube.com/user/nuitcommunications"

# Reading file
include:
exclude:
keep_files:
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posters:
    output: true
    permalink: /:collection/:path/
  visualizations:
    output: true
    permalink: /:collection/:path/
